drone-webdriver/src/main/java/org/jboss/arquillian/drone/webdriver/factory/RemoteWebDriverFactory.java, drone-webdriver/src/main/java/org/jboss/arquillian/drone/webdriver/factory/remote/reusable/ReusableRemoteWebDriverExtension.java, drone-webdriver/src/main/java/org/jboss/arquillian/drone/webdriver/factory/remote/reusable/ReusableRemoteWebDriverToDestroy.java
Implemented a registry ReusableRemoteWebDriverToDestroy where I store the latest driver that was used with a reusable session. Then in AfterClass phase, this webdriver is destroyed. 
The reason is that when the reusable session was persisted, then the remote webdriver instance wasn't destroyed. As a result of this, a browser wasn't closed in tests:
ReusableRemoteWebDriverTestCase
TestReusingRemoteWebDriverSession
=> ARQ-2080 Drone keeps the latest RemoteWebDriver whose reusable session was persisted and in AfterClass it tries to destroy it

depchain/pom.xml, drone-bom/pom.xml, drone-build/pom.xml, drone-webdriver/pom.xml, drone-webdriver/src/main/java/org/jboss/arquillian/drone/webdriver/binary/BinaryFilesUtils.java, drone-webdriver/src/main/java/org/jboss/arquillian/drone/webdriver/binary/downloading/source/GeckoDriverGitHubSource.java, drone-webdriver/src/main/java/org/jboss/arquillian/drone/webdriver/binary/downloading/source/GitHubSource.java, drone-webdriver/src/main/java/org/jboss/arquillian/drone/webdriver/binary/downloading/source/PhantomJSGitHubBitbucketSource.java, drone-webdriver/src/main/java/org/jboss/arquillian/drone/webdriver/binary/handler/AbstractBinaryHandler.java, drone-webdriver/src/main/java/org/jboss/arquillian/drone/webdriver/binary/handler/ChromeDriverBinaryHandler.java, drone-webdriver/src/main/java/org/jboss/arquillian/drone/webdriver/binary/handler/InternetExplorerBinaryHandler.java, drone-webdriver/src/main/java/org/jboss/arquillian/drone/webdriver/binary/handler/PhantomJSDriverBinaryHandler.java, drone-webdriver/src/main/java/org/jboss/arquillian/drone/webdriver/factory/PhantomJSDriverFactory.java, drone-webdriver/src/main/java/org/jboss/arquillian/drone/webdriver/utils/PlatformUtils.java, drone-webdriver/src/main/java/org/jboss/arquillian/drone/webdriver/utils/Validate.java, drone-webdriver/src/test/java/org/jboss/arquillian/drone/webdriver/binary/downloading/source/GitHubSourceLatestReleaseFromTagsTestCase.java, drone-webdriver/src/test/java/org/jboss/arquillian/drone/webdriver/binary/handler/BinaryHandlerTestCase.java, drone-webdriver/src/test/java/org/jboss/arquillian/drone/webdriver/factory/PhantomJSDriverTestCase.java, drone-webdriver/src/test/resources/arquillian.xml, drone-webdriver/src/test/resources/hoverfly/gh.simulation.ariya@phantomjs.tags.json, drone-webdriver/src/test/resources/simple.html, pom.xml
Drone doesn't rely on arquillian-phantom-* projects any more
PhantomJS is downloaded using Spacelift (the logic implemented in Drone and used for other binaries) from Bitbucket download storage
The latest version is retrieved from GH tags.
=> PhantomJS is downloaded using Spacelift

drone-webdriver/src/main/java/org/jboss/arquillian/drone/webdriver/utils/GitHubLastUpdateCache.java, drone-webdriver/src/test/java/org/jboss/arquillian/drone/webdriver/utils/GitHubLastUpdateCacheTest.java
Creating the cache directory failed in case the parent folder did not exist. This lead to errors when storing assets down the road.
=> Failed to create nested cache folder

docs/configuring-drone-instances.adoc, drone-webdriver/src/main/java/org/jboss/arquillian/drone/webdriver/factory/BrowserCapabilitiesList.java, drone-webdriver/src/main/java/org/jboss/arquillian/drone/webdriver/factory/HtmlUnitDriverFactory.java, drone-webdriver/src/main/java/org/jboss/arquillian/drone/webdriver/htmlunit/DroneHtmlUnitDriver.java, drone-webdriver/src/main/java/org/jboss/arquillian/drone/webdriver/htmlunit/HtmlUnitDriver.java, drone-webdriver/src/main/java/org/jboss/arquillian/drone/webdriver/impl/BrowserCapabilitiesRegistryImpl.java, drone-webdriver/src/main/java/org/jboss/arquillian/drone/webdriver/utils/Constants.java, drone-webdriver/src/test/java/org/jboss/arquillian/drone/webdriver/factory/HtmlUnitDriverTest.java, drone-webdriver/src/test/java/org/jboss/arquillian/drone/webdriver/factory/WebClientOptionsMapperTest.java, drone-webdriver/src/test/java/org/jboss/arquillian/drone/webdriver/factory/remote/reusable/TestReusableRemoteWebDriver.java, drone-webdriver/src/test/resources/arquillian.xml
You can add webClientOptions to HtmlUnitDriver.
- Subclassed HtmlUnitDriver to override `protected modifyWebClient()`
- Used desired capabilities to set options from confiiguration to `WebClientOption` 
**Fixes**: #ARQ-1836
=> Adds webClient options to HtmlUnitDriver - ARQ-1836

drone-webdriver/pom.xml, drone-webdriver/src/main/java/org/jboss/arquillian/drone/webdriver/binary/downloading/source/PhantomJSGitHubBitbucketSource.java, drone-webdriver/src/test/java/org/jboss/arquillian/drone/webdriver/binary/downloading/source/GitHubSourceLatestReleaseFromTagsTestCase.java, drone-webdriver/src/test/java/org/jboss/arquillian/drone/webdriver/factory/PhantomJSDriverTestCase.java, drone-webdriver/src/test/resources/arquillian.xml, pom.xml
The reason is that there was announced the end of the development of PhantomJS:
https://groups.google.com/forum/#!msg/phantomjs/9aI5d-LDuNE/5Z3SMZrqAQAJ
so it is expected that there won't be any newer version than the last one: 2.1.1
=> ARQ-2112 As the last PhantomJS release is considered 2.1.1 so Drone won't check if there is any newer one

drone-webdriver/src/main/java/org/jboss/arquillian/drone/webdriver/binary/downloading/source/GitHubSource.java, drone-webdriver/src/main/java/org/jboss/arquillian/drone/webdriver/binary/handler/AbstractBinaryHandler.java, drone-webdriver/src/main/java/org/jboss/arquillian/drone/webdriver/utils/HttpClient.java, drone-webdriver/src/main/java/org/jboss/arquillian/drone/webdriver/utils/PropertySecurityAction.java, drone-webdriver/src/test/java/org/jboss/arquillian/drone/webdriver/binary/downloading/source/GitHubSourceLatestReleaseFromTagsTestCase.java, drone-webdriver/src/test/java/org/jboss/arquillian/drone/webdriver/binary/downloading/source/GitHubSourceLatestReleaseTestCase.java, drone-webdriver/src/test/resources/hoverfly/gh.simulation.mozilla@geckodriver.releases.json
- When a request with the first page is sent, then the parameter is not added -the reason is that conditional requests don't seem to be supported for parametrized requests
- When GH release is retrieved for a version then it check for the presence every page separately (lazily)
- When version is used, check for previous downloads is performed before getting the download URL
- Added logging about sending requests
=> ARQ-2114 It was easy to reach the GH rate limit when firefox is used in large test suites running in CI

drone-webdriver/src/main/java/org/jboss/arquillian/drone/webdriver/binary/downloading/source/ExternalBinarySource.java, drone-webdriver/src/main/java/org/jboss/arquillian/drone/webdriver/binary/downloading/source/GeckoDriverGitHubSource.java, drone-webdriver/src/main/java/org/jboss/arquillian/drone/webdriver/binary/downloading/source/GitHubSource.java, drone-webdriver/src/main/java/org/jboss/arquillian/drone/webdriver/binary/downloading/source/PhantomJSGitHubBitbucketSource.java, drone-webdriver/src/main/java/org/jboss/arquillian/drone/webdriver/binary/handler/AbstractBinaryHandler.java, drone-webdriver/src/main/java/org/jboss/arquillian/drone/webdriver/binary/handler/ChromeDriverBinaryHandler.java, drone-webdriver/src/main/java/org/jboss/arquillian/drone/webdriver/binary/handler/EdgeDriverBinaryHandler.java, drone-webdriver/src/main/java/org/jboss/arquillian/drone/webdriver/binary/handler/InternetExplorerBinaryHandler.java, drone-webdriver/src/main/java/org/jboss/arquillian/drone/webdriver/binary/handler/PhantomJSDriverBinaryHandler.java, drone-webdriver/src/main/java/org/jboss/arquillian/drone/webdriver/binary/handler/SeleniumServerBinaryHandler.java, drone-webdriver/src/test/java/org/jboss/arquillian/drone/webdriver/binary/downloading/source/DummyRepositoryGitHubSource.java, drone-webdriver/src/test/java/org/jboss/arquillian/drone/webdriver/binary/downloading/source/GitHubSourceReleaseForVersionTestCase.java, drone-webdriver/src/test/java/org/jboss/arquillian/drone/webdriver/binary/downloading/source/LocalBinarySource.java, drone-webdriver/src/test/java/org/jboss/arquillian/drone/webdriver/binary/handler/BinaryHandlerDesiredVersionTestCase.java
There are 2 things that have been improved/changed:
* When Drone checks the zip if is already downloaded it takes into account the expected name of the file (based on version and platform)
* GitHub binaries - IAE is thrown for not found versions and a list of available versions is appended to the exception message.
=> improvement in checks in automatic download feature

docs/configuring-drone-instances.adoc, drone-impl/pom.xml, drone-impl/src/main/java/org/jboss/arquillian/drone/impl/DroneTestEnricher.java, drone-impl/src/test/java/org/jboss/arquillian/drone/impl/EnricherTestCase.java, pom.xml
The property is `arquillian.drone.skip.creation`. When it is set to `true` then a Drone instance is not created and injected.
This property is checked in a phase `@Before` so it is possible to modify the property during the test execution.
Fix for issue #93
=> ARQ-2119 Introduced system property for skippping Drone creation/injection

README.adoc, docs/configuring-drone-instances.adoc, drone-webdriver/pom.xml, drone-webdriver/src/main/java/org/jboss/arquillian/drone/webdriver/DroneWebDriverExtension.java, drone-webdriver/src/main/java/org/jboss/arquillian/drone/webdriver/binary/process/SeleniumServerExecutor.java, drone-webdriver/src/main/java/org/jboss/arquillian/drone/webdriver/factory/BrowserCapabilitiesList.java, drone-webdriver/src/main/java/org/jboss/arquillian/drone/webdriver/factory/ChromeDriverFactory.java, drone-webdriver/src/main/java/org/jboss/arquillian/drone/webdriver/factory/RemoteWebDriverFactory.java, drone-webdriver/src/test/java/org/jboss/arquillian/drone/webdriver/factory/ChromeHeadlessDriverTest.java, drone-webdriver/src/test/java/org/jboss/arquillian/drone/webdriver/factory/HeadlessBrowserChromeOptionsTest.java, drone-webdriver/src/test/java/org/jboss/arquillian/drone/webdriver/factory/remote/reusable/MockBrowserCapabilitiesRegistry.java, drone-webdriver/src/test/java/org/jboss/arquillian/drone/webdriver/factory/remote/reusable/TestRemoteWebDriverFactorySessionStoring.java
Currently, the only way to use headless chromium is to use chrome as a browser and then add 
`--headless` as a `chromeArguments` property:
```
<property name="browser">chrome</property>
<property name="chromeArguments">--headless</property>
```
The idea of this task is making it simpler - just using chromeHeadless as a browser property:
```
<property name="browser">chromeHeadless</property>
```
- Adds support for chrome headless browser as a browser property.
- Adds test to verify ChromeHeadlessDriver for a simple loginPage.
**Fixes**: #91
=> Adds chrome headless as Browser property for Drone 

drone-bom/pom.xml, drone-webdriver/src/main/java/org/jboss/arquillian/drone/webdriver/factory/CapabilitiesOptionsMapper.java, drone-webdriver/src/main/java/org/jboss/arquillian/drone/webdriver/factory/ChromeDriverFactory.java, extension/arquillian-drone-appium-extension/README.adoc, extension/arquillian-drone-appium-extension/pom.xml, extension/arquillian-drone-appium-extension/src/main/java/org/arquillian/drone/appium/extension/AppiumExtension.java, extension/arquillian-drone-appium-extension/src/main/java/org/arquillian/drone/appium/extension/DefaultValuesModifier.java, extension/arquillian-drone-appium-extension/src/main/java/org/arquillian/drone/appium/extension/webdriver/AppiumCapabilities.java, extension/arquillian-drone-appium-extension/src/main/java/org/arquillian/drone/appium/extension/webdriver/AppiumDriverFactory.java, extension/arquillian-drone-appium-extension/src/main/resources/META-INF/services/org.jboss.arquillian.core.spi.LoadableExtension, extension/arquillian-drone-appium-extension/src/test/java/org/arquillian/drone/appium/extension/DroneDefaultValuesTest.java, extension/arquillian-drone-appium-extension/src/test/java/org/arquillian/drone/appium/extension/webdriver/AppiumDriverFactoryTest.java, pom.xml
Adds the extension for Appium.
https://issues.jboss.org/browse/ARQ-2038
- Adds the extension
- Allows mapping `ChromeOptions` from outside the package (i.e. to allow the extension to use the mapping mechanics)
**Fixes**: #
With regards to tests. Since full integration tests would require specifically configured environment with Appium server, some mobile virtual device etc., I've created just some unit-like tests.
However, I wasn't sure how to properly test the `instantiationTimeoutInSeconds`, so I "took inspiration" (i.e. basically copied [GlobalDroneConfigurationTestCase](https://github.com/arquillian/arquillian-extension-drone/blob/master/drone-impl/src/test/java/org/jboss/arquillian/drone/impl/GlobalDroneConfigurationTestCase.java)).
Please let me know if it's ok - if not, I'll try to …
=> ARQ-2038 Create Drone extension for Appium

drone-webdriver/src/main/java/org/jboss/arquillian/drone/webdriver/factory/ChromeDriverFactory.java, drone-webdriver/src/main/java/org/jboss/arquillian/drone/webdriver/window/Dimensions.java, drone-webdriver/src/main/java/org/jboss/arquillian/drone/webdriver/window/WindowResizer.java, drone-webdriver/src/test/java/org/jboss/arquillian/drone/webdriver/window/DimensionsPatternTest.java
- Some websites and pages are broken if loaded in a browser window that is half the total screen size of the monitor. Resizing chrome is buggy in latest chrome-drivers and explicitly setting the window size when browser is opened is required.
- Improves the execution speed for Drone Test Suite when using `chromeHeadless` browser, by eliminating waiting time for window resizing. 
- Set window size as argument via chromeOptions.
**Fixes**: #
=> Sets window-size as chrome-option for chrome headless mode.

docs/configuring-drone-instances.adoc, drone-configuration/src/main/java/org/jboss/arquillian/drone/configuration/ConfigurationMapper.java, drone-configuration/src/main/java/org/jboss/arquillian/drone/configuration/mapping/LogLevelMapper.java, drone-webdriver/src/main/java/org/jboss/arquillian/drone/webdriver/factory/CapabilitiesOptionsMapper.java, drone-webdriver/src/main/java/org/jboss/arquillian/drone/webdriver/factory/FirefoxDriverFactory.java, drone-webdriver/src/main/java/org/jboss/arquillian/drone/webdriver/factory/SafariDriverFactory.java
Adds support for FirefoxOptions and SafariOptions.
- Adds support for FirefoxOptions and SafariOptions in the factories.
- Changes a bit the behavior of Firefox capabilities / creating a new profile. The main change is that explicit new profile is created only when necessary. Please see the inline comments for details.
- Adds LogLevelMapper for setting the logLevel in FirefoxOptions.
=> ARQ-2132 Support for FirefoxOptions and SafariOptions

docs/automatic-download.adoc, drone-webdriver/src/main/java/org/jboss/arquillian/drone/webdriver/binary/handler/InternetExplorerBinaryHandler.java, drone-webdriver/src/main/java/org/jboss/arquillian/drone/webdriver/binary/handler/SeleniumServerBinaryHandler.java, drone-webdriver/src/test/java/org/jboss/arquillian/drone/webdriver/binary/handler/GoogleSeleniumStorageProvider.java
Adds the support for specifying the architecture for IE driver binary.
Includes some fixes as well - please see bellow.
- Basically adds `ieDriverArch` property. If it's not specified then it just falls back to the original behavior - downloads the binary based on the OS architecture.
- Adds proper emptiness check for `ieDriverVersion` and `seleniumServerVersion`. Before, when those properties were specified but empty, it caused `StringIndexOutOfBoundsException`.
**Fixes**: #
`StringIndexOutOfBoundsException`
=> ARQ-2140 Support for specifying the architecture for IE driver binary

drone-webdriver/src/main/java/org/jboss/arquillian/drone/webdriver/factory/CapabilitiesOptionsMapper.java, drone-webdriver/src/test/java/org/jboss/arquillian/drone/webdriver/factory/CapabilitiesChromeOptionsMapperTest.java
the option mapper checks if the value is a json or primitive type to support also:  
```xml
<extension qualifier="webdriver">
<property name="chromeExperimentalOption">
{
"useAutomationExtension": "false"
}
</property>
</extension>
```
**Fixes**: #114
=> fix(chromeOptions): When experimental option json is parsed then it checks what is the type of the value

drone-webdriver/src/main/java/org/jboss/arquillian/drone/webdriver/factory/CapabilitiesOptionsMapper.java, drone-webdriver/src/test/java/org/jboss/arquillian/drone/webdriver/factory/CapabilitiesChromeOptionsMapperTest.java
Unfortunately, the fix for https://github.com/arquillian/arquillian-extension-drone/issues/114 does not work with selenium. I should have specified the json primitive false instead of the string "false". 
This pull requst allows one to specify a boolean: 
```
<property name="chromeExperimentalOption">
{
"useAutomationExtension": false
}
</property>
```
=> Allow typed primitive option values other than strings

drone-webdriver/src/main/java/org/jboss/arquillian/drone/webdriver/binary/BinaryFilesUtils.java, drone-webdriver/src/main/java/org/jboss/arquillian/drone/webdriver/binary/downloading/Downloader.java, drone-webdriver/src/main/java/org/jboss/arquillian/drone/webdriver/binary/handler/AbstractBinaryHandler.java, drone-webdriver/src/main/java/org/jboss/arquillian/drone/webdriver/utils/Constants.java, drone-webdriver/src/main/java/org/jboss/arquillian/drone/webdriver/utils/GitHubLastUpdateCache.java, drone-webdriver/src/test/java/org/jboss/arquillian/drone/webdriver/binary/handler/BinaryHandlerTestCase.java, extension/arquillian-drone-browserstack-extension/src/main/java/org/arquillian/drone/browserstack/extension/local/BrowserStackLocalRunner.java, extension/arquillian-drone-saucelabs-extension/src/main/java/org/arquillian/drone/saucelabs/extension/connect/SauceConnectRunner.java
I changed most of the `File` usages to `Path`. It will be easier to keep the whole path by using the fluent API instead of joining strings and `File.separator`
In addition, I changed the relative paths to absolute ones as it was causing an issue in non-forked tests.
=> fix(ARQ-2154): refactored usage of files to nio Path & changed relative paths to absolute

drone-bom/pom.xml
=> fix(#126): removes arquillian-drone-selenium-server from BOM

.travis.yml
Oldest oraclejdk seems to be JDK9 on Travis right now, switching to OpenJDK instead.
=> fix(ci): switches to openjdk8 for travis builds

drone-webdriver/src/main/java/org/jboss/arquillian/drone/webdriver/binary/downloading/source/GitHubSource.java, drone-webdriver/src/main/java/org/jboss/arquillian/drone/webdriver/utils/HttpClient.java, drone-webdriver/src/test/java/org/jboss/arquillian/drone/webdriver/utils/HttpClientResponseTest.java
- header names should be case-insensitive
- also fallback to "now" when the Last-Modified header is absent
We're observing problems with downloading the latest Firefox driver due to the fact that a response from the GitHub API contains a header with name `last-modified` but drone expects `Last-Modified`. As a result a `NullPointerException` is thrown from a [ZonedDateTime.parse()](https://github.com/arquillian/arquillian-extension-drone/blob/master/drone-webdriver/src/main/java/org/jboss/arquillian/drone/webdriver/binary/downloading/source/GitHubSource.java#L145) invocation.
=> fix(download): case insensitive headers in HttpClient.Response

drone-bom/pom.xml, drone-build/pom.xml, drone-impl/src/test/java/org/jboss/arquillian/drone/impl/DestroyerTestCase.java, drone-impl/src/test/java/org/jboss/arquillian/drone/impl/DroneContextFilteringTest.java, drone-impl/src/test/java/org/jboss/arquillian/drone/impl/EnhancerTestCase.java, drone-impl/src/test/java/org/jboss/arquillian/drone/impl/GlobalDroneConfigurationTestCase.java, drone-impl/src/test/java/org/jboss/arquillian/drone/impl/InjectionPointsTest.java, drone-impl/src/test/java/org/jboss/arquillian/drone/impl/RegistrarTestCase.java, drone-webdriver/pom.xml, drone-webdriver/src/main/java/org/jboss/arquillian/drone/webdriver/augmentation/AugmentingEnhancer.java, drone-webdriver/src/main/java/org/jboss/arquillian/drone/webdriver/factory/BrowserCapabilitiesList.java, drone-webdriver/src/main/java/org/jboss/arquillian/drone/webdriver/factory/EdgeDriverFactory.java, drone-webdriver/src/main/java/org/jboss/arquillian/drone/webdriver/factory/FirefoxDriverFactory.java, drone-webdriver/src/main/java/org/jboss/arquillian/drone/webdriver/factory/SafariDriverFactory.java, drone-webdriver/src/main/java/org/jboss/arquillian/drone/webdriver/factory/remote/reusable/ReusableRemoteWebDriver.java, drone-webdriver/src/test/java/org/jboss/arquillian/drone/webdriver/factory/FirefoxDriverFactoryTest.java, drone-webdriver/src/test/java/org/jboss/arquillian/drone/webdriver/factory/remote/reusable/TestPrivateAccessCompatibility.java, drone-webdriver/src/test/java/org/jboss/arquillian/drone/webdriver/factory/remote/reusable/TestReusedSessionStore.java, drone-webdriver/src/test/java/org/jboss/arquillian/drone/webdriver/factory/remote/reusable/TestReusedSessionStoreImplSerialization.java, pom.xml
This PR provides support for upcoming Selenium 4. At this moment, the most recent released version of Selenium is 4.0.0-RC-2. This PR prepares for full support of Selenium 4. After releasing GA, it's necessary to do some changes in pom files regarding versions properties. Moreover, _htmlUnitDriver_ will be released soon with Selenium 4 compatibility.
There are some failing tests for WebDriver caused by PhantomJS incompatibility with Selenium 4 and some issues with TLS certificate in GitHub tests.
Initial support for #272
=> feat: provides interoperability with Selenium 4

drone-webdriver/src/main/java/org/jboss/arquillian/drone/webdriver/binary/handler/AbstractBinaryHandler.java
Throw `IllegalStateException` in case the downloaded file passed to `AbstractBinaryHandler.prepare` doesn't exist in order to avoid less intuitive error message during extraction.
Non-intuitive error message in case a downloaded binary vanishes after download
- Throw IllegalStateException if downloaded file vanished
=> fix: fails when previously downloaded file doesn't exist

drone-webdriver/src/main/java/org/jboss/arquillian/drone/webdriver/binary/handler/ChromeDriverBinaryHandler.java
Use the M1 build of the Goggle Chrome WebDriver on Apple Silicon
There is an extra build of Google Chrome WebDriver for Apple Silicon. The name of the binary has an additional _m1 at the end. The x64 driver essentially works but starts Chrome in Rosetta. The M1 binary speeds the tests quit significantly.
=> feat(chrome): downloads driver version for Apple Silicon

.circleci/config.yml
This way we avoid leaving any left-overs such as `LICENSE.chromedriver` in the working directory leading to failure on git clone, as the directory is not empty.
=> fix: runs browser-tools scripts in /tmp folder

drone-webdriver/src/main/java/org/jboss/arquillian/drone/webdriver/binary/handler/ChromeDriverBinaryHandler.java
ChromeDriver 109.0.5414.25 changed the contents of the driver archive to include a license file (`LICENSE.chromedriver`). When `ChromeDriverBinaryHandler` prepares the driver it attempts to make this license file executable which causes an exception to be raised:
```text
INFO: Extracting zip file: /home/jenkins/.arquillian/drone/chrome/109.0.5414.74/chromedriver_linux64.zip to /home/jenkins/workspace/example/target/drone/245747a6d5f2b7da02c465941f43e0e8
Jan 11, 2023 11:39:47 AM org.jboss.arquillian.drone.webdriver.binary.handler.AbstractBinaryHandler markAsExecutable
INFO: marking binary file: /home/jenkins/workspace/example/target/drone/245747a6d5f2b7da02c465941f43e0e8/LICENSE.chromedriver as executable
/home/jenkins/workspace/example/target/drone/245747a6d5f2b7da02c465941f43e0e8/LICENSE. …
```
=> fix(chromedriver): ensures to extract binary

.circleci/config.yml
Sets env variable of `OPENSSL` for nodejs to unblock the tests. 
See https://github.com/nodejs/node/issues/43132\#issuecomment-1130503287
=> fix: unblocks phantomjs build

.circleci/config.yml
CI builds on the `v2-support` branch are failing due to git clone errors caused by browser-tools leaving files in the working directory. This has been solved in the `master` branch.
Applies the CI changes made in ea4b04d and #376.
=> fix(ci): backports CI changes to 2.x

drone-webdriver/src/main/java/org/jboss/arquillian/drone/webdriver/binary/handler/ChromeDriverBinaryHandler.java
Backports the fix in #373 to 2.x. This resolves download issues introduced by the addition of a license file (`LICENSE.chromedriver`) in the ChromeDriver archive.
This PR changes the logic to find the ChromeDriver binary by filename instead of grabbing the first file.
Fixes #381
=> fix(v2/chromedriver): backports ChromeDriver LICENSE fix

drone-webdriver/src/main/java/org/jboss/arquillian/drone/webdriver/factory/remote/reusable/SerializationWhitelist.java
removed Compiler.class from serialization whitelist due to incompatibility with JDK 21
JDK 21 runtime compatibility
=> v2: JDK 21 runtime compatibility 

drone-webdriver/src/main/java/org/jboss/arquillian/drone/webdriver/factory/CapabilitiesOptionsMapper.java
resolves issue #565 allowing any map for complex properties. It is in the hands of the configurator how the map is created.
The PR just avoids using Map<String,String> and uses only Map.class instead.
**Fixes**: #565
=> Allow typed primitive option values other than strings in maps

drone-webdriver/src/main/java/org/jboss/arquillian/drone/webdriver/augmentation/AugmentingEnhancer.java, drone-webdriver/src/test/java/org/jboss/arquillian/drone/webdriver/binary/process/SeleniumServerTestCase.java
Removes workarounds for test suites broken by Selenium since 4.29.0
Once workarounds are no longer necessary, the test suite will pass
Fixes #549
Related issue: https://github.com/SeleniumHQ/selenium/issues/15323
=> Remove workarounds

drone-webdriver/src/main/java/org/jboss/arquillian/drone/webdriver/configuration/WebDriverConfiguration.java, drone-webdriver/src/main/java/org/jboss/arquillian/drone/webdriver/factory/CapabilitiesOptionsMapper.java, drone-webdriver/src/main/java/org/jboss/arquillian/drone/webdriver/factory/ChromeDriverFactory.java, drone-webdriver/src/main/java/org/jboss/arquillian/drone/webdriver/factory/EdgeDriverFactory.java, drone-webdriver/src/main/java/org/jboss/arquillian/drone/webdriver/factory/FirefoxDriverFactory.java
Selenium BiDi (bidirectional browser comm via WebSocket) has been implemented
This PR adds ability to turn BiDi on via configuration:
`<property name="enableBidi">true</property>`
May also require
`<property name="unhandledPromptBehaviour">ignore</property>` to prevent bidi from auto-dismissing dialogs
fixes #545
=> enh: add functionality to enable BIDI via configuration
